### ISSUE TITLE
Navigation custom fieldset

### ISSUE THREAD

**Issue by hmalaud** [statamic/ideas#564] opened 2021-05-31 15:14 UTC
Most of the times, navigation links have classes, IDs, or are just pictograms; currently, it is impossible to add more data to a navigation link than just an URL and a label, when an ID field would be a real tool to have more customization possibilities. Ideally, being able to specify the navigation blueprint would be really great.

**Comment by jackmcdade** [comment] 2021-05-31 15:15
This is a duplicate of our most frequently requested feature – #175. It's currently on deck, in planning. Sorry to close it so quickly but just wanted to give you the status!

**Closed by jackmcdade** 2021-05-31 15:15 UTC

**Comment by hmalaud** [comment] 2021-05-31 15:17
Don't be sorry, I'm the one who should be for not checking first!
