### ISSUE TITLE
Ability to remove the slug on a collection

### ISSUE THREAD

**Issue by austriker27** [statamic/ideas#424] opened 2021-01-05 17:25 UTC
I would like the ability to remove the slug from a collection. 

I tried removing the `slug` from blueprint, or hiding it via conditions but it keeps showing up. 

This is useful for situations where the collection doesn't have a URL (and isn't connected to a route). Although if this data is better in `globals` feel free to close this idea. 

It will help clients from getting confused who try to click the 'visit URL' button or change the slug.

**Comment by j3ll3yfi5h** [comment] 2021-01-05 17:38
maybe the easiest solution would be allowing `hidden: true` on that field...

**Comment by robdekort** [comment] 2021-03-17 08:55
This seems a duplicate of https://github.com/statamic/ideas/issues/390 but is a great idea nonetheless.

**Comment by aerni** [comment] 2021-03-23 17:33
I'd love to see this implemented. Very useful for collections like `orders`, `customers`, and the like that will never be public.

**Comment by jonassiewertsen** [comment] 2021-03-23 17:37
We are building a custom System with Statamic, with custom endpoints to export the data. 

Besides @aerni examples, the slug is not helpful in our case either.

**Comment by aerni** [comment] 2021-03-24 07:58
I think it would also make sense to have the ability to remove the `title` from the blueprint. Not all collections need a title.

**Comment by afonic** [comment] 2021-05-20 09:02
I agree with @aerni. There are some cases where a Collection's `Title` and `Slug` fields are not really needed. For example a client of mine needs a huge Collection named `Offers` which has thousands of offers we then display in the frontend in a table format.

Right now to handle this we either:

- Ask the client to add a "random" title (something he generates manually - like `OFFER + CODE + N`)
- Use a Laravel Eloquent model using SQLite and a custom `index` page.

Ideally, we would configure a Collection to not used those fields but just generate a filename automatically.

There are a couple of way this could work:

- An "auto incrementing" `Collection` using an auto incrementing ID that could be saved as an index somewhere, much like a normal ID field in a database
- Use the randomly generated ID or an item as the filename

I guess given the latest work to allow duplicate slugs this could be easier to implement than before.

**Comment by jonassiewertsen** [comment] 2021-05-20 09:54
Could or would it work, to use the `id` as a filename somehow? 

I'd imagine putting a setting into the collection, saying `slugify: false`. If set to false, the id will be used as filename, otherwise everthing will work as before and the filename will be generate from the slug.

**Closed** 2021-12-13 20:04 UTC
