### ISSUE TITLE
Make custom fieldtype available in forms

### ISSUE THREAD

**Issue by albaur** [statamic/ideas#431] opened 2021-01-11 09:49 UTC
Hi, I've created my own field types and some of them I need to be able to use in form blueprints as well. I found that in `vendor/statamic/cms/src/Http/Controllers/CP/Fields/FieldtypesController.php` there's a list that defined which fieldTypes are supported in forms:

```
private function supportedInForms($fieldtype) { 
    return in_array($fieldtype, [
        'assets',
        'checkboxes', 
        'integer', 
        'radio',
        'select', 
        'text', 
        'textarea', 
        'custom_field_type'
    ]); 
}
```

We should be able to overwrite this array or extend it, so we can add custom fieldtypes to the form. At the moment on every composer update my field gets deleted

**Comment by jasonvarga** [comment] 2021-01-11 15:57
Duplicate of #409

**Closed by jasonvarga** 2021-01-11 15:57 UTC
