### ISSUE TITLE
FR: Feature request for custom navigation blueprints

### ISSUE THREAD

**Issue by andrew-ireland** [statamic/ideas#455] opened 2021-02-02 06:23 UTC
I've run into an edge case building a Mega Menu. Erin mentioned on discord it could be a good FR.

Long story short, I want to build a navigation structure which is 3 levels deep. On the third level, I need to output a description for each link. For the 'Link to entry' this is simple enough, as I can customise the blueprint accordingly for pages. Unfortunately though, if I use a 'Link to URL',  it doesn't seem like I can customise the blueprint shown here (or at least I wasn't able to in testing). Is it possible to add additional fields in this panel, or does anyone have a workaround that doesn't suck?'

I've attached an image to show what I mean! Alternatively, are there any other ways you would recommend I tackle this?

![Screen Shot 2021-02-02 at 4 09 02 pm](https://user-images.githubusercontent.com/18650897/106560460-29b45900-657b-11eb-9714-3b3081335efa.png)

**Comment by damcclean** [comment] 2021-02-02 07:21
Duplicate of #135.

**Closed** 2021-03-01 20:02 UTC
