### ISSUE TITLE
Entry list view: display if entry is a link/redirect

### ISSUE THREAD

**Issue by wturrell** [statamic/ideas#970] opened 2023-03-29 17:05 UTC
At the moment, if an entry is a link/redirect, there's no obvious way of telling so in Collection list view (other than from memory). 

Redirects still have their own slug, so you can't tell from that.

You could add the Redirect column, but that takes up loads of space because of the nature of URLs.

You _can_ filter by blueprint, but it requires 5 mouse clicks.

Suggest adding something to Customize Columns, probably rendered as an icon - there are obvious choices for both links and entries - to avoid losing too much horizontal space.

**Comment by duncanmcclean** [comment] 2024-03-12 23:01
Duplicate of #923.

**Closed by duncanmcclean** 2024-03-12 23:01 UTC
