### ISSUE TITLE
Show Actions on Entry Page

### ISSUE THREAD

**Issue by sbrow** [statamic/ideas#1149] opened 2024-04-14 19:40 UTC
AFAIK, right now actions are visible on collection pages, but you can't see them when you visit a specific entry. It'd be great if there was a way to do this, either by default, or possibly with a new "Actions" Fieldtype?

**Comment by joshuablum** [comment] 2024-04-15 07:04
Duplicate of https://github.com/statamic/ideas/issues/712.

There’s also an open PR for this, see https://github.com/statamic/cms/pull/6375.

**Closed as completed** 2024-04-15 08:28 UTC
Labels: duplicate
