### ISSUE TITLE
Use related entry slug in route

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#852] opened 2022-08-18 16:45 UTC
I think this has been mentioned before but I wanted to use an entry's slug in another entry's route. e.g.
`/{relatedEntrySlug}/{slug}`

The related entry is set up using an entries field with max items = 1.

With the above route defined in my control panel I get the related entry's ID rather than it's slug in my urls. I guess this could get complicated if the related entry has a complex url itself.

I have also tried renaming the field to 'mount' in an attempt to override the mounted entry, but that doesn't work.

Thanks.

**Comment by jasonvarga** [comment] 2022-08-18 17:02
Duplicate of #360

**Closed by jasonvarga** 2022-08-18 17:02 UTC
