### ISSUE TITLE
Improve UI when having many replicator sets

### ISSUE THREAD

**Issue by morhi** [statamic/ideas#605] opened 2021-07-20 07:47 UTC
When having many replicator sets it can get unclear or confusing when you want to insert a new set. It looks like this:

![Bildschirmfoto 2021-07-20 um 09 48 41](https://user-images.githubusercontent.com/12037294/126282507-e577638a-92dd-4afd-a8db-4c1ead97e0c2.png)

I'd suggest to think about a better UI/UX, perhaps with an optional Icon for a set, so that it is easier to understand what a set is about.

**Comment by jasonvarga** [comment] 2021-07-20 13:37
Duplicate of #361

**Closed by jasonvarga** 2021-07-20 13:37 UTC
