### ISSUE TITLE
CP: Add Users search and filter

### ISSUE THREAD

**Issue by mikemartin** [statamic/ideas#393] opened 2020-11-23 23:56 UTC
Is adding search/filter for users on the roadmap? One of my clients have over 6000 users and when they have to lookup a user it can be pretty cumbersome.

**Comment by jasonvarga** [comment] 2020-11-24 03:02
Yup. Duplicate of statamic/cms#1796, basically.

**Closed by jasonvarga** 2020-11-24 03:02 UTC

**Comment by mikemartin** [comment] 2020-11-24 07:16
Fair dinkum @jasonvarga
