### ISSUE TITLE
FR: Let handle of blueprints and fieldsets be editable in CP

### ISSUE THREAD

**Issue by manogi** [statamic/ideas#40] opened 2019-11-24 09:53 UTC
If I am not mistaken, the handle of blueprints and fieldsets cannot be edited on create or later in the CP. This would be great, as I like to have my handles in English while most of my titles are in German for my German customers. 

I know I can always switch to the yaml file and change the filename, but that is not quite as speedy.

Thanks! I am really excited about Statamic now being a Laravel package - so many advantages!

**Comment by goellner** [comment] 2020-02-13 12:54
Would be nice, if it was the same logic as for the slug fields.

**Comment by jasonvarga** [comment] 2020-04-20 15:12
Duplicate of statamic/cms#1667

**Closed by jasonvarga** 2020-04-20 15:12 UTC
Labels: feature request
