### ISSUE TITLE
Pin Collection(s) To Content Menu

### ISSUE THREAD

**Issue by tobyjug** [statamic/ideas#242] opened 2020-07-22 19:47 UTC
I find the term 'Collection' to be quite developer-focused, and more often than not, clients are used to the idea of 'pages' being the primary aspect of a site – therefore, it would be nice to be able to make the Pages collection (or any other collection for that matter) a first-class citizen of the Content menu in the sidebar.

In addition to this, it would be nice to be able hide the Collection menu item altogether, leaving just links to the available collections directly in the sidebar. For example, a client would log in and see:

CONTENT
– Pages
– News
– Jobs

**Comment by jasonvarga** [comment] 2020-07-22 20:42
Duplicate of #74

**Closed by jasonvarga** 2020-07-22 20:42 UTC
