### ISSUE TITLE
Conditional display of Sections/Tabs

### ISSUE THREAD

**Issue by thomas4Bitcraft** [statamic/ideas#1031] opened 2023-08-14 11:45 UTC
have a Section/Tab in a Blueprint containing fields only visible if a specific category is set. Unfortunately, the fields are hidden as expected, but the Section/Tab Header is still showing. As far as I see there is currently no possibility to hide these.

**Comment by jasonvarga** [comment] 2023-08-14 14:24
Duplicate of https://github.com/statamic/cms/issues/7855

**Closed by jasonvarga** 2023-08-14 14:24 UTC
