### ISSUE TITLE
Customization of taxonomy permalink structure

### ISSUE THREAD

**Issue by godismyjudge95** [statamic/ideas#1054] opened 2023-09-20 20:04 UTC
Would be nice to be able to customize the permalink structure for a taxonomy.

I found this useful when I want the taxonomy named with an internal nomenclature but need the public facing url to be something a little more user friendly.

**Comment by jasonvarga** [comment] 2023-09-20 21:42
Duplicate of https://github.com/statamic/cms/issues/2403 and being worked on in https://github.com/statamic/cms/pull/8627

**Closed by jasonvarga** 2023-09-20 21:42 UTC

**Comment by godismyjudge95** [comment] 2023-09-20 22:10
@jasonvarga sorry for the duplicates, I must have missed that in my search.  Also you guys are 🔥  getting my features/issues fixed before I get a chance to create a PR 😂
