### ISSUE TITLE
Allow sorting/filtering collections by key of an array

### ISSUE THREAD

**Issue by klickreflex** [statamic/ideas#722] opened 2022-01-04 15:12 UTC
Date range fields would be more powerful if their start and end date could be used to manipulate the output of the collection tag. T

Right now, it's not possible to sort or filter a collection by a date range field (as in: a single date field that accepts a start and an  end date).

So instead of querying like this:

```
  sort="market_date:start:asc"
  market_date:end:gte="{today format='Y-m-d'}"
```

We need to have dedicated fields for both the start and end date - and worse, we lose the nice UX of the datepicker for range selection, which increases chances for bad input  (e.g. start date after end date).

**Comment by jasonvarga** [comment] 2022-01-04 15:22
Duplicate of #428

**Closed by jasonvarga** 2022-01-04 15:22 UTC
