### ISSUE TITLE
Dynamic Asset File Path

### ISSUE THREAD

**Issue by schwartzmj** [statamic/ideas#901] opened 2022-10-31 19:47 UTC
I'm looking to save certain uploaded files into a dynamic path, probably WordPress style e.g. `/{currentYear}/{currentMonth}/filename.pdf` or even `/{taxonomy-slug}/filename.pdf`.

I've tested listening for various Entry and Asset events, but I'm not finding a way to do it this way.

I propose allowing us to use Antlers to set a dynamic filepath for an Asset field, similar to how Titles and Routes work when setting up a collection.

**Comment by jasonvarga** [comment] 2022-10-31 19:51
Duplicate of #725

**Closed by jasonvarga** 2022-10-31 19:51 UTC
