### ISSUE TITLE
Save / Save and New

### ISSUE THREAD

**Issue by dambridge** [statamic/ideas#310] opened 2020-09-09 22:15 UTC
Finding some basic workflows a bit cumbersome, that may be improved with something like the following.

When creating a new resource, be it a Collection, Entry, Blueprint, whatever, have the option to either just save it and return to the index screen for that resource, or 'Save and New', which would save the current item and refresh the current screen/blueprint to start creating another one.

Make sense?

**Comment by jasonvarga** [comment] 2020-09-09 22:17
Sounds like a duplicate of https://github.com/statamic/cms/issues/675 👍

**Closed by jasonvarga** 2020-09-09 22:17 UTC

**Comment by dambridge** [comment] 2020-09-09 22:22
Indeed it is, sorry about that.

**Comment by jasonvarga** [comment] 2020-09-09 22:23
No problem! Actually, you brought up that it should work in other places, like Blueprints. That's a good idea too. Maybe leave a comment on that issue?

**Comment by jackmcdade** [comment] 2020-09-09 22:48
It's also in the works! 👍
