### ISSUE TITLE
Make asset meta information localizable

### ISSUE THREAD

**Issue by fjahn** [statamic/ideas#484] opened 2021-03-05 15:34 UTC
This is a follow-on [this question on the forum](https://statamic.com/forum/5263-localizaton-for-asset-fields). The OP tried to localize the alt text of an asset. Apparently, this is not currently possible.

The OP did come up with a workaround by duplicating the assets, which is obviously not satisfying at all.

**Comment by jasonvarga** [comment] 2021-03-05 15:41
Duplicate of #223

**Closed by jasonvarga** 2021-03-05 15:41 UTC
