### ISSUE TITLE
Show collection name when multiple collection types available in entry selector

### ISSUE THREAD

**Issue by stuartcusackie** [statamic/ideas#819] opened 2022-06-16 15:46 UTC
I don't think there's any way to distinguish between two entries from separate collections that share the same title, so you just have to guess. Screenshot:

![image](https://user-images.githubusercontent.com/20210934/174111430-7aa8aaf3-15b6-46c4-9425-9a2acf1fe1e6.png)

Thanks.

**Comment by edalzell** [comment] 2022-06-16 16:51
Duplicate of https://github.com/statamic/ideas/issues/507, I think.

**Comment by jacksleight** [comment] 2022-08-15 17:06
Just run into this on a site with a bunch of collections that often have identically named entries. Listing the collection and maybe even the blueprint as well would be really helpful.

For now I'm playing around with a workaround. It feels like a bit of a hack and I have no idea if it'll make something break horribly, but so far that hasn't happened. 🤞

Entries store their blueprint handles, so you can get those to output in the listing by adding a hidden field called `blueprint` to all of the applicable blueprints:

```yaml
-
  handle: blueprint
  field:
    type: hidden
    display: Blueprint
    listable: true
```

![Screenshot 2022-08-15 at 17 55 07](https://user-images.githubusercontent.com/126740/184681445-b48c214c-0e7e-4379-9104-4a630cee1d3b.png)

Caveats:

* This only works for the blueprint name not the collection name
* It will also appear in the regular entry listing
* Could haven unintended side-effects?

**Comment by stuartcusackie** [comment] 2022-08-24 09:57
Yep, I would like to be able to see the blueprint name in the listing as well. I think if a collection has multiple blueprints then this should happen by default.

**Closed** 2022-08-25 10:52 UTC
