### ISSUE TITLE
Show blueprint title on pages tree view

### ISSUE THREAD

**Issue by mmodler** [statamic/ideas#1117] opened 2024-01-26 07:25 UTC
I think it would be very useful to show the blueprint title on the page tree view:

![grafik](https://github.com/statamic/ideas/assets/1906217/efd16d46-96fc-4c6e-b6d9-e824e01ca19b)

I would only show blueprint titles if there are two ore more blueprints. And we can add this information to the page create/edit view, too.

A layout alternative would be the style of entries fieldtype:
![grafik](https://github.com/statamic/ideas/assets/1906217/fc6f2d72-df8c-4f5a-bf77-c97393fb9937)

I like to hear your thoughts before working on it seriously. Thanks!

**Comment by mmodler** [comment] 2024-01-26 07:31
A layout alternative would be the style of entries fieldtype:
![entries](https://github.com/statamic/ideas/assets/1906217/bbefe246-b786-4e08-9fe9-f9c131b1c247)

**Comment by duncanmcclean** [comment] 2024-01-26 07:38
Duplicate of #854.

**Closed** 2024-01-26 07:38 UTC
