### ISSUE TITLE
Folder selection for asset field (dynamic asset field)

### ISSUE THREAD

**Issue by Cabbidachi** [statamic/ideas#1124] opened 2024-02-10 17:39 UTC
Basically
You select a folder instead of files for an asset field. And then whenever you add images to that folder they will be automatically added to the asset field. I think i have a very specific use-case but it would really help me out since i have a gallery with different years and everytime i upload new images i have to select them in the asset field.

**Comment by duncanmcclean** [comment] 2024-03-12 22:05
Duplicate of #772.

**Closed by duncanmcclean** 2024-03-12 22:05 UTC
Labels: duplicate
