### ISSUE TITLE
[4.x] - Add ability to share/import whole blueprints

### ISSUE THREAD

**Issue by ceesvanegmond** [statamic/ideas#1143] opened 2024-03-12 21:45 UTC
"Since 4.x, it's possible to add namespaced blueprints (https://github.com/statamic/docs/issues/1232), which is nice! But I'm looking for a way to share blueprints across collections. Of course, I can import fieldsets, but ideally, I want to import the whole blueprint so I can reuse the same blueprint across multiple collections. 

I've done some debugging, but you cannot use this new namespaced blueprints feature for this. Is this true? Is there another way?

**Comment by duncanmcclean** [comment] 2024-03-12 22:00
There's no way to do this currently.

Duplicate of #1102.

**Closed by duncanmcclean** 2024-03-12 22:00 UTC
