### ISSUE TITLE
Add option in Bard field to link to pages/collections

### ISSUE THREAD

**Issue by jmartsch** [statamic/ideas#236] opened 2020-07-17 13:12 UTC
In #234 I describe how the UI of adding links inside a bard field could be optimized.
In addition to this, it would be good, if there was a simple way to link to internal entries/collections.

In ProcessWire when you add a link, you get a modal and can enter either a URL, or select a page or a file you would like to link to.
![image](https://user-images.githubusercontent.com/551551/87789619-9ebe7c00-c83f-11ea-9350-f3d29fadc84e.png)

Demo how to select pages
![image](https://user-images.githubusercontent.com/551551/87789401-47b8a700-c83f-11ea-8c2e-9994ceadb751.png)

There is also an attributes tab where you can set the target, and the rel of the link (for example nofollow).
![image](https://user-images.githubusercontent.com/551551/87789741-ce6d8400-c83f-11ea-90ec-0c9a72bc0323.png)

**Comment by FlorianMoser** [comment] 2020-09-04 08:27
This was available in v2. No idea why it's missing in v3.

**Comment by robdekort** [comment] 2020-10-13 14:23
Duplicate of #217 and #234

**Comment by jmartsch** [comment] 2020-10-13 16:25
@robdekort This isn't exactly a duplicate. This is the request for implementing this option. #234 is a description how the UI might look.

**Comment by robdekort** [comment] 2020-10-14 08:51
@jmartsch You’re right. Updated the comment! It might be nice for the gents to merge all this into one FR. But then you lose upvotes right?

**Closed** 2021-04-02 13:50 UTC
