### ISSUE TITLE
Multisite: Entries fieldtype add possibility to select entries from other sites

### ISSUE THREAD

**Issue by wm-simon** [statamic/ideas#778] opened 2022-04-06 15:30 UTC
Some collections are used for multiple sites. For example I have a site with blog articles and the articles should shown on multiple sites. Right know, I have to add them for each site separately, because I can not select entries from other sites anymore. 
I know, this was a changed in the past, but perhaps it would be the best way, to give the devs the possibility to change it in the fieldtype settings, perhaps like the site selector in the collection settings.

**Comment by aerni** [comment] 2023-12-19 19:13
Duplicate of https://github.com/statamic/ideas/issues/778.

**Comment by wm-simon** [comment] 2023-12-19 19:16
> Duplicate of #778.

Oh no, this loop will never end...

**Comment by j3ll3yfi5h** [comment] 2023-12-20 08:51
He means #646 😄

**Comment by aerni** [comment] 2023-12-20 14:00
Haha yes, my bad 😅

**Comment by duncanmcclean** [comment] 2023-12-20 14:05
I'm going to close this in favour of the the other issue (it has some more details/comments).

**Closed** 2023-12-20 14:06 UTC
