### ISSUE TITLE
Support for first_name last_name instead of name when searching for an Eloquent User.

### ISSUE THREAD

**Issue by jeverington** [statamic/ideas#818] opened 2022-06-16 13:54 UTC
Statamic supports first_name and last_name for a signup, etc, but it's not when searching for users. I am using Statamic with users in a database.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'where clause' (SQL: select count(*) as aggregate from `users` where (`email` like %dsdd% or `name` like %dsdd%) and `users`.`deleted_at` is null)

**Comment by ryanmitchell** [comment] 2022-06-20 06:26
I get around this by making a 'name' column with a trigger that concatenates both first_name and last_name

**Comment by duncanmcclean** [comment] 2024-03-13 15:14
I'm unable to reproduce this issue on the latest version of Statamic. I can search by `first_name` and `last_name` columns just fine, as long as the fields exist in my user blueprint.

I'm going to close this issue now. If you're still experiencing this issue, please leave a comment and we can re-open the issue. Thanks!

**Closed as completed by duncanmcclean** 2024-03-13 15:14 UTC
