### ISSUE TITLE
Add conditions to linked fieldsets

### ISSUE THREAD

**Issue by websmyth** [statamic/ideas#781] opened 2022-04-12 17:02 UTC
We’re frequently pulling in small partial fieldsets into blueprints and other fieldsets. It would be great if we could conditionally load these in a similar way to the conditional loading of standard (non-linked) fieldsets.

For instance, we might have a button partial: we’d want to pull that into other fieldsets/blueprints but not want it to display all the time. Ideally, we could add a toggle (or button group etc) on the blueprint/parent fieldset and apply a `show_when` condition to the linked fieldset (the button).

Here’s a hopefully-helpful 120 second explainer...
https://www.loom.com/share/df6f8dfac42d4ada97683ed778916f0e

**Comment by austriker27** [comment] 2022-06-08 18:08
I would love this as well. I use fieldsets often for the same sort of thing (aka button like Dave above) and it would be nice to only conditionally show it.

**Comment by robdekort** [comment] 2022-11-22 11:25
Duplicate of https://github.com/statamic/ideas/issues/451

**Closed** 2022-11-22 17:33 UTC
