### ISSUE TITLE
Support for preview URLs 

### ISSUE THREAD

**Issue by goellner** [statamic/ideas#306] opened 2020-09-08 14:59 UTC
It would be great to support preview URLs in the cms. Those can be used by headless frontends and maybe for normal setups with Statamic too. It would generate a token and the preview url could be shared with people, who are not registered cms users.

More info on that topic and our specific use case: https://nextjs.org/docs/advanced-features/preview-mode

There are a few examples which showcase different CMSs that support preview urls.

**Comment by jasonvarga** [comment] 2020-09-08 15:31
Duplicate of #161

**Closed by jasonvarga** 2020-09-08 15:31 UTC
