### ISSUE TITLE
Grouping Sets on the Replicator field

### ISSUE THREAD

**Issue by lokmanm** [statamic/ideas#518] opened 2021-04-21 13:34 UTC
Hey Statamic folks,

In a recent project we have to build a very large website with 90+ pages and each page basically its build with a replicator that contains multiple sets and they are used as building blocks to build pages. Think of this as a visual builder for their website.

So the issue we have is that if you have a lot of Sets, they will all be displayed in a vertical list that is not very UX friendly.
It will be very good if you can group/organize them in a cleaner way.

If the core team thinks this is a good idea, I might pitch this at our company so we can maybe open a PR.

Thanks

**Comment by jackmcdade** [comment] 2021-04-21 13:37
Do you have any idea of what a "cleaner way" would be? Also, have you thought about using Bard instead, as it's often used for content-focused building block type layouts.

**Comment by lokmanm** [comment] 2021-04-21 13:42
Hey @jackmcdade thanks for the quick reply. 

Doesn't the same issue stand even with bard ? Assume you have 20+ sets the `Add set` button will display them all in one vertical list, at least thats what happens in our end. 

I have a few ideas we might try to conceptualize and post them here.

**Comment by lokmanm** [comment] 2021-04-21 15:08
Okay,

So this is just one idea for multi level dropdown for organizing sets maybe someone has a better approach at this.

Basically the idea I have posted here revolves around this.

![proposal](https://user-images.githubusercontent.com/11158157/115576819-23a15f00-a2c4-11eb-820c-750380ef8f34.jpg)

**Comment by jasonvarga** [comment] 2021-04-21 15:39
Thanks for the issue! It's a duplicate of #361 though.

**Closed by jasonvarga** 2021-04-21 15:39 UTC

**Comment by lokmanm** [comment] 2021-04-21 15:56
Thanks @jasonvarga, had no idea. I will follow it there.

**Comment by jackmcdade** [comment] 2021-04-21 16:23
My apologies @lokmanm, I was thinking you meant the actual _rendered_ sets with the content in it. I was gonna say I just can't think of any drastically different way to do that lol
