### ISSUE TITLE
Make Bard and Replicator fields localizable, please?

### ISSUE THREAD

**Issue by axelferdinand** [statamic/ideas#731] opened 2022-01-12 14:46 UTC
As of now, only top-level fields are localizable. This is the root to a lot of pain and suffering for poor editors trying to update multisites featuring a lot of languages.

Imagine this:

1. You create a huge entry with a lot of text and images using the magnificent Bard fieldset.
2. You translate the entry to 10 languages using the incredible multisite functionality built in Statamic.
3. You realize that one of the photos sucks, so you head to the default language and update the picture.
4. Time goes by, and to fear and indignation you discover that the Dutch version of the site still uses the old photo! And that is the case for 8 other languages as well...
5. Sad and sorry, you log in to Statamic and begin the tedious job with replacing the photo on the 9 other languages...

It doesn't have to be this way. Simply make Bard and Replicator fields localizable 🎉

**Comment by jasonvarga** [comment] 2022-01-12 14:49
Duplicate of #439

**Closed by jasonvarga** 2022-01-12 14:49 UTC
