### ISSUE TITLE
Generate slug from multiple fields

### ISSUE THREAD

**Issue by aerni** [statamic/ideas#938] opened 2023-01-18 14:40 UTC
I think it would be a nice feature if we could generate the slug from multiple fields. Similar to how we can already do it with the [title format](https://statamic.dev/collections#titles) of collection entries.

In this example, I want to generate the slug from the entry's title and date:

```yaml
handle: slug
field:
  type: slug
  from: '{title} {date}'
```

**Comment by jasonvarga** [comment] 2023-02-21 17:24
Duplicate of #532

**Closed by jasonvarga** 2023-02-21 17:24 UTC
